### PR TITLE
modify the layout

### PR DESCRIPTION
**Pull request by SquidAnan**
1. The position, size, colors of the homepage title and subtitle
2. The layout(title size, background color, font-size) of each card

### CODE REVIEW

**Comment by SquidAnan** [comment]
There is another stylesheet now and the old one remains

**Comment by idoleat** [comment]
If `Homepage2.css` is based on `Homepage.css` and should be linked after `Homepage.css`, duplicated classes are not needed. Like what [theme_squiggle_pattern.css](https://github.com/idoleat/SafeHouse/blob/master/styles/theme_squiggle_pattern.css) did.

If `Homepage2.css` is intended to be another stand-alone style sheet, it looks good to be merged.

**Comment by idoleat** [comment]
I should implement theme editor soon so that we can preview all the available style sheets....

**Comment by idoleat** [comment]
I'll move the following
> If Homepage2.css is based on Homepage.css and should be linked after Homepage.css, duplicated classes are not needed. Like what [theme_squiggle_pattern.css](https://github.com/idoleat/SafeHouse/blob/master/styles/theme_squiggle_pattern.css) did.

to issue and merge this PR.

**Comment by idoleat** [comment]
Actually it is my responsibility to craft a style editor that can include a base style. Before that any style is fine to be a free standing style cause there's no standard way to base on another one.

**Pull request merged**
